device: "cuda"
run: "dummy"
seed: 1337
dtype: "bfloat16"

ddp:
  use: false
  rank: 0
  local_rank: 0
  world_size: 1
  broadcast_buffers: false

log:
  log_level: "INFO"
  use_stream_handler: true
  use_file_handler: true
  logs_dir: "logs"

matmul_tf32: "high"
cudnn_tf32: true
cudnn_sdp: false 
flash_sdp: true
mem_efficient_sdp: false
math_sdp: false

dataset_name: "FineWeb"
train_data: "data/datasets/fineweb10B_sp1024/fineweb_train_*.bin"
val_data: "data/datasets/fineweb10B_sp1024/fineweb_val_*.bin"

tokenizer_name: "SentencePiece"
tokenizer_path: "data/tokenizers/fineweb_1024_bpe.model"

model:
  vocab_size: 1024
  architecture: "gpt"
  components:
    linear_type: "CastedLinear"
  control_tensor_name_patterns: [
    "attn_scale", "attn_scales", "mlp_scale", "mlp_scales", "resid_mix", 
    "resid_mixes", "q_gain", "skip_weight", "skip_weights"
  ]
  restore_low_dim_params_in_fp32: true
  compile:
    use: true
    dynamic: false
    fullgraph: true

training:
  train_seq_len: 1024
  metrics: ["bpb"]

validation:
  val_batch_size: 524288
  val_loss_every: 1000
  train_log_every: 200

  